import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

const root = new URL('..', import.meta.url).pathname;
const read = (relative) => readFileSync(`${root}/${relative}`, 'utf8');

test('website and WebView downloads use the supplied listing and the correct latest APK', () => {
  const page = read('index.html');
  const install = read('app/js/part012.js');
  const listing = read('nowssb-listing-2.html');
  const workflow = read('.github/workflows/android-apk.yml');
  const flutterWorkflow = read('.github/workflows/flutter-apk.yml');
  const middleware = read('functions/_middleware.js');

  assert.match(page, /nowssb-listing-2\.html/);
  assert.match(install, /window\.location\.href = '\.\/nowssb-listing-2\.html'/);
  assert.match(listing, /nowssb-android\/NowssB-Android\.apk/);
  assert.match(listing, /nowssb\.com\/download\/flutter\.apk/);
  assert.match(listing, /inCapacitorWebView/);
  assert.match(listing, /window\.nwsbIsNative/);
  assert.match(listing, /Plugins && capacitor\.Plugins\.Browser/);
  assert.match(listing, /window\.location\.assign\(apk\)/);
  assert.match(listing, /window\.goBack/);
  assert.match(listing, /role="button"/);
  assert.match(listing, /listing-hero/);
  assert.match(listing, /assets\/app-listing\/listing-hero-banner\.png/);
  assert.match(listing, /hero-back-btn/);
  assert.match(listing, /background:#fff/);
  assert.doesNotMatch(listing, /Download the app<br>/);
  assert.doesNotMatch(listing, /class="page-title"/);
  assert.doesNotMatch(listing, /header-divider/);
  assert.match(listing, /scroll-track/);
  assert.match(listing, /gallery-track/);
  assert.match(listing, /data-auto-direction="1"/);
  assert.match(listing, /data-auto-direction="-1"/);
  assert.match(listing, /requestAnimationFrame\(tick\)/);
  assert.match(listing, /assets\/app-listing\/listing-01\.webp/);
  assert.match(listing, /loading="lazy"/);
  assert.match(listing, /NowssB-Flutter-Android\.apk/);
  assert.doesNotMatch(listing, /data:image/);
  assert.doesNotMatch(listing, /artifacts\/download/);
  assert.match(workflow, /permissions:\s*\n\s+contents: write/);
  assert.match(workflow, /Publish direct NowssB APK/);
  assert.match(workflow, /PUBLIC_FILE=NowssB-Android\.apk/);
  assert.match(flutterWorkflow, /Publish direct Flutter APK and update manifest/);
  assert.match(flutterWorkflow, /PUBLIC_FILE=NowssB-Flutter-Android\.apk/);
  assert.match(middleware, /url\.pathname === '\/download\/flutter\.apk'/);
  assert.match(middleware, /Content-Disposition/);
  assert.match(middleware, /application\/vnd\.android\.package-archive/);
});
