import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const index = readFileSync(new URL("../index.html", import.meta.url), "utf8");
const registry = readFileSync(new URL("../app/js/part062.js", import.meta.url), "utf8");
const flutter = readFileSync(new URL("../flutter_app/lib/screens/home_normal.dart", import.meta.url), "utf8");
const flutterDashboard = readFileSync(new URL("../flutter_app/lib/screens/normal/neomorphic_dashboard.dart", import.meta.url), "utf8");
const flutterEssentials = readFileSync(new URL("../flutter_app/lib/screens/normal/neomorphic_essentials.dart", import.meta.url), "utf8");
const flutterActionBar = readFileSync(new URL("../flutter_app/lib/screens/normal/neomorphic_action_bar.dart", import.meta.url), "utf8");
const directSections = readFileSync(new URL("../app/js/part095-direct-neomorphic-sections.js", import.meta.url), "utf8");
const styles = readFileSync(new URL("../nowssb-nm.css", import.meta.url), "utf8");
const dashboard = readFileSync(new URL("../app/widgets/neomorphic_dashboard.html", import.meta.url), "utf8");
const essentials = readFileSync(new URL("../app/widgets/neumorphic-essentials.html", import.meta.url), "utf8");
const actionBar = readFileSync(new URL("../app/widgets/neomorphic-action-bar-1.html", import.meta.url), "utf8");

const searchAt = index.indexOf('class="nmh-search"');
const dashboardAt = index.indexOf('class="nmh-supplied-dashboard"');
const essentialsAt = index.indexOf('class="nmh-supplied-essentials"');
const mainOpsAt = index.indexOf('class="mainops-blk nmh-sec-wrap"');
const actionBarAt = index.indexOf('class="nmh-supplied-actionbar"');
assert.ok(searchAt >= 0 && dashboardAt > searchAt, "WebView dashboard must follow Normal Home search");
assert.ok(essentialsAt > dashboardAt, "WebView essentials must follow the dashboard");
assert.ok(actionBarAt > mainOpsAt, "WebView action bar must follow Normal Home Where to Begin");
assert.match(index, /data-direct-neomorphic="dashboard"/, "WebView must reserve a direct dashboard host");
assert.match(index, /data-direct-neomorphic="essentials"/, "WebView must reserve a direct essentials host");
assert.match(index, /data-direct-neomorphic="actionbar"/, "WebView must reserve a direct action-bar host");
assert.doesNotMatch(index, /<iframe\b/, "WebView must not use external iframes for the supplied sections");
assert.match(index, /part095-direct-neomorphic-sections\.js/, "WebView must load the direct section renderer");
assert.match(directSections, /attachShadow/, "Direct renderer must mount supplied styles inside the page");
assert.match(directSections, /neomorphic_dashboard\.html/, "Direct renderer must use the supplied dashboard document");
assert.match(directSections, /neumorphic-essentials\.html/, "Direct renderer must use the supplied essentials document");
assert.match(directSections, /neomorphic-action-bar-1\.html/, "Direct renderer must use the supplied action-bar document");
assert.match(directSections, /transparentHost/, "Direct renderer must remove the Essentials host background");
assert.doesNotMatch(styles, /\.nmh-supplied-dashboard\s*\{[^}]*height:/s, "Host must not reserve a fixed empty height");
assert.doesNotMatch(styles, /\.nmh-supplied-dashboard\s*\{[^}]*box-shadow:/s, "Host must not add another dashboard wrapper shadow");
assert.doesNotMatch(styles, /\.nmh-supplied-essentials\s*\{[^}]*height:/s, "Essentials host must not reserve a fixed empty height");
assert.doesNotMatch(styles, /\.nmh-supplied-essentials\s*\{[^}]*box-shadow:/s, "Essentials host must not add another wrapper shadow");
assert.doesNotMatch(dashboard, /class="phone"/, "Dashboard must not retain the large outer phone wrapper");
assert.doesNotMatch(essentials, /class="phone"/, "Essentials must not retain the large outer phone wrapper");
assert.doesNotMatch(actionBar, /min-height:\s*100vh/, "Action bar must not retain the supplied document's full-page outer wrapper");
assert.match(dashboard, /dashboardMetricToday/, "Dashboard must expose a live sessions-today metric");
assert.match(directSections, /nowssbDirectDashboardRender/, "Direct renderer must receive live dashboard values");
assert.match(directSections, /runDashboardAction/, "Direct renderer must route dashboard actions in the page");
assert.match(directSections, /See less/, "Direct renderer must preserve the supplied essentials expand behavior");
assert.match(directSections, /wireActionBar/, "Direct renderer must wire the supplied action-bar controls");
assert.match(directSections, /placeActionBar/, "Direct renderer must force the coach bar below Where to Begin");
assert.match(directSections, /startDashboardPractice/, "Dashboard actions must start the playable practice session");
assert.match(index, /part094-dashboard-live\.js/, "Normal Home must load the live dashboard controller");
assert.match(registry, /k:'dashboard'[\s\S]*sel:\['\.nmh-supplied-dashboard'\][\s\S]*after:'search'/, "Dashboard must remain anchored below search");
assert.match(registry, /k:'essentials'[\s\S]*sel:\['\.nmh-supplied-essentials'\][\s\S]*after:'dashboard'/, "Essentials must remain anchored below the dashboard");
assert.match(registry, /k:'actionbar'[\s\S]*sel:\['\.nmh-supplied-actionbar'\][\s\S]*after:'mainops'/, "Action bar must remain anchored below Where to Begin");
assert.ok(flutter.indexOf("'search'") < flutter.indexOf("'dashboard'"), "Flutter dashboard must follow search in Normal Home order");
assert.ok(flutter.indexOf("'dashboard'") < flutter.indexOf("'essentials'"), "Flutter essentials must follow the dashboard");
assert.ok(flutter.indexOf("'mainops'") < flutter.indexOf("'actionbar'"), "Flutter action bar must follow Where to Begin");
assert.match(flutter, /NmSuppliedDashboard\(onStart: _openDashboardSession, onProgress: _openDashboardProgress\)/, "Flutter must wire the dashboard to its real player and progress screen");
assert.match(flutter, /\('essentials', const NmSuppliedEssentials\(\)\)/, "Flutter must render essentials directly after the dashboard");
assert.match(flutterDashboard, /PracticeProgress\.instance/, "Flutter dashboard must use persistent user session data");
assert.match(flutterDashboard, /Plays aloud/, "Flutter dashboard must identify the audible session behavior");
assert.match(flutter, /bottomNavigationClearance/, "Flutter Normal Home must reserve space above the floating navigation");
assert.match(flutterEssentials, /See more/, "Flutter must preserve the supplied essentials expand control");
assert.match(flutterActionBar, /How can we help today\?/, "Flutter must preserve the supplied action-bar text");

console.log("Supplied dashboard is anchored below Normal Home search in WebView and Flutter.");
