import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const index = readFileSync(new URL("../index.html", import.meta.url), "utf8");
const flow = readFileSync(new URL("../app/js/part093-support-flow.js", import.meta.url), "utf8");
const firebase = readFileSync(new URL("../app/js/firebase.module.js", import.meta.url), "utf8");
const admin = readFileSync(new URL("../admin.html", import.meta.url), "utf8");
const rules = readFileSync(new URL("../firestore.rules", import.meta.url), "utf8");
const worker = readFileSync(new URL("../worker.js", import.meta.url), "utf8");

assert.match(index, /onclick="openHelpSupport\(\)"/, "Chat Support must open the Help and Support destination");
assert.match(index, /app\/widgets\/help-support\.html/, "The supplied Help and Support page must be embedded");
assert.match(index, /nwsbSupportChat/, "The dark support chat container must be present");
assert.match(index, /nwsbSupportCaseStatus/, "The support chat must expose a case-submission status region");
assert.match(index, /nwsbMySupportCases/, "The Help and Support flow must include a My Support Cases screen");
assert.match(index, /nwsbMySupportCasesFilter/, "My Support Cases must include a filter dropdown");
assert.match(index, /Active cases/, "The support-case filter must offer active cases");
assert.match(index, /Resolved cases/, "The support-case filter must offer resolved cases");
assert.match(flow, /\/api\/assistant\/chat/, "Support messages must use the existing secured AI route");
assert.match(flow, /Submitting your support case/, "Escalation must show a loading message while submission is in progress");
assert.match(flow, /submitted successfully/, "Escalation must show a clear success confirmation");
assert.match(flow, /setCaseStatus\('submitting'\)/, "The spinner must be activated before the case submission requests complete");
assert.match(flow, /makeCaseReference/, "Each escalated case must receive a reference number");
assert.match(flow, /Reference:/, "The success confirmation must display the case reference");
assert.match(flow, /openMySupportCases/, "Users must be able to open their support-case history");
assert.match(flow, /View conversation history/, "Users must be able to view each case conversation history");
assert.match(flow, /In Progress/, "Users must see an In Progress badge for active cases");
assert.match(flow, /supportCaseState/, "My Support Cases must normalize Open, In Progress, and Resolved states");
assert.match(flow, /filterMySupportCases/, "My Support Cases must re-render when the user changes the case filter");
assert.match(flow, /filterSupportRows/, "My Support Cases must filter cached rows without widening Firestore access");
assert.match(index, /nwsb-support-case-status/, "The submission status region must use dedicated presentation styles");
assert.match(flow, /body\.needsHuman \|\| state\.intent === 'feedback'/, "Reports must escalate only when the AI cannot resolve them");
assert.doesNotMatch(flow, /state\.intent === 'report'/, "Report selection alone must not bypass AI-first support");
assert.match(flow, /window\._fbCreateSupportReport/, "Escalated support cases must be persisted for the admin interface");
assert.match(firebase, /window\._fbCreateSupportReport/, "Firebase must expose authenticated support-case creation");
assert.match(firebase, /collection\(db, 'reports'\)/, "Support cases must use the protected reports collection");
assert.match(firebase, /caseReference/, "The support case reference must persist with the report");
assert.match(firebase, /window\._fbGetMySupportReports/, "Firebase must expose a signed-in user case-history query");
assert.match(firebase, /where\('reporterUid', '==', user\.uid\)/, "User support history must query only the signed-in reporter");
assert.match(rules, /allow list: if isAdmin\(\) \|\| \(signedIn\(\) && resource\.data\.reporterUid == request\.auth\.uid\);/, "Firestore rules must allow a signed-in user to list only their own support cases");
assert.match(admin, /SUPPORT CASES/, "The admin dashboard must contain a Support Cases inbox");
assert.match(admin, /watchSupportCases\(\)/, "The admin dashboard must watch incoming support cases");
assert.match(admin, /Case /, "The admin inbox must display the support case reference");
assert.match(admin, /Start progress/, "The admin inbox must support moving a case to In Progress");
assert.match(admin, /in_progress/, "The admin inbox must persist the In Progress state");
assert.match(worker, /\/api\/support\/escalate/, "The worker must expose a background escalation route");
assert.match(worker, /caseReference/, "The background escalation must retain the support case reference");
assert.match(worker, /RESEND_API_KEY/, "The worker must use a server-side Resend credential");
assert.match(worker, /SUPPORT_TO_EMAIL/, "The worker must use a server-side recipient binding");
assert.doesNotMatch(worker, /nowssbonline@gmail\.com/, "The recipient must not be hardcoded into Worker source");

console.log("Support flow static contract verified.");
