/// The Android home-screen widget — practice streak + word of the day.
///
/// The widget itself (RemoteViews layout, `NowssbHomeWidget` provider,
/// manifest receiver) is generated by tools/flutter-android.mjs. This file
/// feeds it: it writes the streak, the last day you practised and the word
/// of the day for today and the next six days into home_widget's storage,
/// so the widget rolls over at midnight on its own and works offline, then
/// asks Android to redraw it. Widget taps come back as `nowssb://widget/…`
/// URIs (see [HomeWidgetSync.clicks]).
library;

import 'dart:async';
import 'dart:io' show Platform;

import 'package:flutter/foundation.dart';
import 'package:home_widget/home_widget.dart';

import 'content.dart';
import 'models.dart';
import 'practice_progress.dart';

class HomeWidgetSync {
  HomeWidgetSync._();
  static final HomeWidgetSync instance = HomeWidgetSync._();

  /// The provider class (namespace com.nowssb.nowssb, not the application
  /// id com.nowssb.app — hence the fully qualified name).
  static const qualifiedName = 'com.nowssb.nowssb.NowssbHomeWidget';

  /// Days of words written ahead, so the widget needs no app for a week.
  static const daysAhead = 7;

  static bool get supported => !kIsWeb && Platform.isAndroid;

  bool _started = false;
  String _lastPayload = '';
  Timer? _debounce;

  // home_widget keeps returning the launch URI for the activity's lifetime,
  // so the cold-start tap is handed out once per process; a NavShell mounted
  // later (sign-out → sign-in) must not replay it.
  static bool _initialHandled = false;

  /// Taps on the widget (cold start included), as `nowssb://widget/<what>`.
  Stream<Uri> get clicks async* {
    if (!supported) return;
    if (!_initialHandled) {
      _initialHandled = true;
      final first = await HomeWidget.initiallyLaunchedFromHomeWidget().catchError((_) => null);
      if (first != null) yield first;
    }
    await for (final u in HomeWidget.widgetClicked) {
      if (u != null) yield u;
    }
  }

  Future<void> start() async {
    if (_started || !supported) return;
    _started = true;
    PracticeProgress.instance.addListener(_schedule);
    ContentStore.instance.addListener(_schedule);
    await PracticeProgress.instance.start();
    await push();
    // Redraw just after each coming midnight so the word and the streak
    // state roll over even if the app is not opened (inexact is fine).
    try {
      final now = DateTime.now();
      await HomeWidget.scheduleWidgetUpdates(
        [
          for (var d = 1; d <= daysAhead; d++)
            DateTime(now.year, now.month, now.day + d, 0, 1),
        ],
        qualifiedAndroidName: qualifiedName,
      );
    } catch (e) {
      debugPrint('NowssB widget schedule: $e');
    }
  }

  void _schedule() {
    _debounce?.cancel();
    _debounce = Timer(const Duration(milliseconds: 600), () => unawaited(push()));
  }

  static String day(DateTime d) =>
      '${d.year}-${d.month.toString().padLeft(2, '0')}-${d.day.toString().padLeft(2, '0')}';

  /// The word of the day for [date]: the same pick on every phone, from the
  /// free words when there are any (so "Practise" opens without a lock).
  static Word? wordFor(DateTime date, List<Word> library) {
    if (library.isEmpty) return null;
    final free = [for (final w in library) if (w.price <= 0) w];
    final pool = free.isNotEmpty ? free : library;
    final index = DateTime.utc(date.year, date.month, date.day)
            .difference(DateTime.utc(2024, 1, 1))
            .inDays %
        pool.length;
    return pool[index < 0 ? index + pool.length : index];
  }

  static String lineFor(Word w) {
    final bits = <String>[
      if (w.deva.trim().isNotEmpty) w.deva.trim(),
      if (w.meaning.trim().isNotEmpty)
        w.meaning.trim()
      else if (w.benefit.trim().isNotEmpty)
        w.benefit.trim()
      else if (w.origin.trim().isNotEmpty)
        w.origin.trim(),
    ];
    return bits.join(' · ');
  }

  /// Everything the widget shows, keyed as NowssbHomeWidget.kt reads it.
  static Map<String, String> payload({
    required DateTime now,
    required List<Word> library,
    required int streak,
    required String? lastDay,
  }) {
    final out = <String, String>{
      'nw_streak': '$streak',
      'nw_last_day': lastDay ?? '',
    };
    for (var d = 0; d < daysAhead; d++) {
      final date = DateTime(now.year, now.month, now.day + d);
      final w = wordFor(date, library);
      if (w == null) continue;
      out['nw_word_${day(date)}'] = w.word;
      out['nw_line_${day(date)}'] = lineFor(w);
      if (d == 0) {
        out['nw_word_fallback'] = w.word;
        out['nw_line_fallback'] = lineFor(w);
      }
    }
    return out;
  }

  Future<void> push() async {
    if (!supported) return;
    final p = PracticeProgress.instance;
    final data = payload(
      now: DateTime.now(),
      library: ContentStore.instance.library,
      streak: p.streak,
      lastDay: p.lastPracticed,
    );
    final sig = data.entries.map((e) => '${e.key}=${e.value}').join('|');
    if (sig == _lastPayload) return;
    try {
      for (final e in data.entries) {
        await HomeWidget.saveWidgetData<String>(e.key, e.value);
      }
      await HomeWidget.updateWidget(qualifiedAndroidName: qualifiedName);
      _lastPayload = sig;
    } catch (e) {
      debugPrint('NowssB widget: $e');
    }
  }

  /// Adds the widget to the home screen (launchers that support pinning).
  Future<bool> requestPin() async {
    if (!supported) return false;
    try {
      if (await HomeWidget.isRequestPinWidgetSupported() != true) return false;
      await HomeWidget.requestPinWidget(qualifiedAndroidName: qualifiedName);
      return true;
    } catch (_) {
      return false;
    }
  }
}
