/* Generated by tools/economy/gen-word-ids.py from the bundled library. Do not edit. */
export const BUNDLED_WORD_IDS = new Set(["aarogya", "ananda", "chandra", "kapha", "ojas", "pitta", "prana", "shakti", "soma", "surya", "tejas", "vata"]);
