// Fills flutter_app/assets/ before a Flutter build.
//
// The clips live in one place in this repository — assets/video/ — because
// the website and the app show the same films and a second copy is a second
// copy to keep in step. So flutter_app/assets/video/ is NOT committed; it is
// filled from assets/video/ on the way into a build, the same way www/ is
// filled by tools/build-native.mjs.
//
//   node tools/flutter-assets.mjs
//
// Run this BEFORE `flutter pub get`. A directory named in pubspec.yaml's
// assets: block that does not exist fails pub get outright, so this is not
// optional and it is not an optimisation — it is a build step.
//
// It also writes the shipped content, by calling tools/export-content.mjs,
// so one command puts everything the bundle needs in place.

import { readdirSync, mkdirSync, copyFileSync, statSync, existsSync,
         readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
/* The folders that go into the bundle. Not only the clips: the app's own
   artwork lives here too and is what makes it look like NowssB rather than
   like a Material demo — the device bezels the televisions are drawn from,
   the intro-page paintings, the logo disc, the collection banners. All of
   it is already in this repository; none of it needed downloading. */
const FOLDERS = [
  'video',        // the clips and their posters
  'frames',       // the device bezels — see lib/widgets/tv_frame.dart
  'icons',        // the logo disc, the search mark
  'store',        // the intro-page artwork, and the collection covers
  'fashion',      // the Fashion Plus intro and its icon
  'player',       // the player's own artwork
  'signature',    // the Signature's marks
  'certificates',
  'banners',      // the collection banners
];

const KEEP = /\.(mp4|webp|png|jpe?g|svg)$/i;

let copied = 0, skipped = 0, bytes = 0;

function copyDir(rel) {
  const from = join(root, 'assets', rel);
  const to = join(root, 'flutter_app', 'assets', rel);
  if (!existsSync(from)) return;
  mkdirSync(to, { recursive: true });

  for (const name of readdirSync(from)) {
    const src = join(from, name);
    const s = statSync(src);
    if (s.isDirectory()) { copyDir(join(rel, name)); continue; }
    if (!KEEP.test(name)) continue;

    const dst = join(to, name);
    // Same size and not older: already there. Makes a re-run cheap, which
    // matters when this is 200 MB.
    if (existsSync(dst)) {
      const d = statSync(dst);
      if (d.size === s.size && d.mtimeMs >= s.mtimeMs) {
        skipped++; bytes += s.size; continue;
      }
    }
    copyFileSync(src, dst);
    copied++; bytes += s.size;
  }
}

for (const f of FOLDERS) copyDir(f);

console.log(
  `flutter_app/assets/  ${copied} copied, ${skipped} already current, ` +
  `${(bytes / 1024 / 1024).toFixed(1)} MB total`
);

/* ── The URL → bundled-file map ────────────────────────────────────────
   lib/media/nwsb_image.dart reads this. A section names a picture by the
   URL index.html uses; this says whether that picture is on disk yet.

   Written from the manifest and filtered to what has ACTUALLY been
   downloaded, so a URL in the map is a promise the bundle can keep. Until
   `node tools/asset-manifest.mjs --download` runs, the map is nearly empty
   and every section falls back — which is the designed state, not a
   failure. */
const manifestPath = join(root, 'assets', 'media-manifest.json');
const mapOut = join(root, 'flutter_app', 'lib', 'media', 'media_map.dart');

let entries = [];
if (existsSync(manifestPath)) {
  const m = JSON.parse(readFileSync(manifestPath, 'utf8'));
  entries = m.assets || m.entries || m;
  if (!Array.isArray(entries)) entries = [];
}

const have = entries.filter(
  (e) => e && e.url && e.local &&
         existsSync(join(root, 'assets', 'media', e.local)),
);

// Copy the downloaded media in too — it is only useful to the app if it is
// in the bundle beside everything else.
if (have.length) {
  mkdirSync(join(root, 'flutter_app', 'assets', 'media'), { recursive: true });
  for (const e of have) {
    const src = join(root, 'assets', 'media', e.local);
    const dst = join(root, 'flutter_app', 'assets', 'media', e.local);
    mkdirSync(dirname(dst), { recursive: true });
    if (!existsSync(dst) || statSync(dst).size !== statSync(src).size) {
      copyFileSync(src, dst);
    }
  }
}

writeFileSync(
  mapOut,
  '// GENERATED by tools/flutter-assets.mjs — do not edit by hand.\n' +
  '//\n' +
  '// The address a section names, and the file in the bundle that answers\n' +
  '// it. Only URLs that have actually been downloaded appear here; the rest\n' +
  '// fall back, which is what lib/media/nwsb_image.dart is for.\n' +
  '//\n' +
  '//   node tools/asset-manifest.mjs --download   fetches them\n' +
  '//   node tools/flutter-assets.mjs              rebuilds this\n' +
  'library;\n\n' +
  'const Map<String, String> kNowssbMedia = {\n' +
  have.map((e) => `  ${JSON.stringify(e.url)}: 'assets/media/${e.local}',`)
      .join('\n') +
  (have.length ? '\n' : '') +
  '};\n',
);
console.log(`lib/media/media_map.dart  ${have.length} of ${entries.length} downloaded`);

execFileSync(process.execPath, [join(root, 'tools', 'export-content.mjs')], {
  stdio: 'inherit',
});
