// GENERATED by tools/flutter-assets.mjs — do not edit by hand.
//
// The address a section names, and the file in the bundle that answers
// it. Only URLs that have actually been downloaded appear here; the rest
// fall back, which is what lib/media/nwsb_image.dart is for.
//
//   node tools/asset-manifest.mjs --download   fetches them
//   node tools/flutter-assets.mjs              rebuilds this
library;

const Map<String, String> kNowssbMedia = {};
