#!/usr/bin/env python3
"""Writes functions/_lib/economy/word_ids.js from the bundled library
(flutter_app/assets/content/library.json) so the server can tell a real
word from a made-up one. Re-run after the bundled library changes; words
the admin publishes later are checked against words/{id} in Firestore."""
import json, re, pathlib
root = pathlib.Path(__file__).resolve().parents[2]
lib = json.loads((root / 'flutter_app/assets/content/library.json').read_text())
ids = set()
for it in lib.get('items', []):
    for k in ('key', 'word'):
        v = re.sub(r'[^a-z0-9_-]', '', str(it.get(k) or '').lower())[:60]
        if v: ids.add(v)
out = root / 'functions/_lib/economy/word_ids.js'
out.write_text('/* Generated by tools/economy/gen-word-ids.py from the bundled library. Do not edit. */\nexport const BUNDLED_WORD_IDS = new Set(' + json.dumps(sorted(ids)) + ');\n')
print(len(ids), 'word ids ->', out)
